version: "3"
services:
  user:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
    volumes:
      - ./:/go/src/github.com/nigoroku/amb-user
    ports:
      - "8081:8081"
    environment:
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    tty: true
    stdin_open: true
