version: "3"
services:
  user:
    build:
      context: .
    volumes:
      - ./:/go/src/github.com/nigoroku/amb-user
    ports:
      - "8081:8081"
    environment:
      - DATABASE_HOST=amb-db
      - DATABASE_PASSWORD=base0210
      - DATABASE=ambitious
      - DATABASE_USERNAME=root
    tty: true
    stdin_open: true
    networks:
      - amb-network

networks:
  amb-network:
    external: true
