FROM golang:1.14.10-alpine3.12 as builder

WORKDIR /go/src/github.com/nigoroku/amb-user
ADD . /go/src/github.com/nigoroku/amb-user

ENV GO111MODULE=on

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/amb-user

FROM alpine:latest

RUN apk update && apk add --no-cache ca-certificates
COPY --from=builder /go/bin/amb-user /go/bin/amb-user

ENTRYPOINT ["/go/bin/amb-user"]
EXPOSE 8081