FROM golang:1.14.10-alpine3.12 as builder

WORKDIR /go/src/github.com/nigoroku/amb-user
ADD . /go/src/github.com/nigoroku/amb-user

ENV GO111MODULE=on

RUN apk update && apk add --no-cache ca-certificates && update-ca-certificates

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/amb-user

FROM scratch

COPY --from=builder /go/bin/amb-user /go/bin/amb-user

EXPOSE 8081

ENTRYPOINT ["/go/bin/amb-user"]
