// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	InputAchievementTags  string
	InputAchievements     string
	MCategories           string
	OutputAchievementTags string
	OutputAchievements    string
	ShareTokens           string
	TodoDetails           string
	Todos                 string
	Users                 string
}{
	InputAchievementTags:  "input_achievement_tags",
	InputAchievements:     "input_achievements",
	MCategories:           "m_categories",
	OutputAchievementTags: "output_achievement_tags",
	OutputAchievements:    "output_achievements",
	ShareTokens:           "share_tokens",
	TodoDetails:           "todo_details",
	Todos:                 "todos",
	Users:                 "users",
}
