// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("InputAchievementTags", testInputAchievementTagsUpsert)

	t.Run("InputAchievements", testInputAchievementsUpsert)

	t.Run("MCategories", testMCategoriesUpsert)

	t.Run("OutputAchievementTags", testOutputAchievementTagsUpsert)

	t.Run("OutputAchievements", testOutputAchievementsUpsert)

	t.Run("TodoDetails", testTodoDetailsUpsert)

	t.Run("Todos", testTodosUpsert)

	t.Run("Users", testUsersUpsert)
}
